# Generated by Django 5.0.6 on 2024-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_spent_amount_alter_goal_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(default='RON', max_length=3),
        ),
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='RON', max_length=3),
        ),
        migrations.AlterField(
            model_name='goal',
            name='saved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
