# Generated by Django 5.0.6 on 2024-12-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_currency_goal_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='currency',
        ),
    ]
