# Generated by Django 5.0.6 on 2024-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_category_currency_remove_goal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(default='RON', max_length=3),
        ),
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='RON', max_length=3),
        ),
    ]
